title: Home Assistant
views:
  - title: Главная
    icon: mdi:home-assistant
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            title: Температура
            cards:
              - type: gauge
                name: Зал
                entity: sensor.0x00158d000464e067_temperature
                min: 10
                max: 45
              - type: gauge
                name: Спальня
                entity: sensor.0x00158d0004658739_temperature
                min: 10
                max: 45
          - type: glance
            title: Протечки
            entities:
              - entity: binary_sensor.0x00158d00042f219f_water_leak
                name: 1
              - entity: binary_sensor.0x00158d00042fd07e_water_leak
                name: 2
              - entity: binary_sensor.0x00158d00045a552a_water_leak
                name: 3
          - type: weather-forecast
            entity: weather.home_assistant

      - type: vertical-stack
        cards:
          - type: horizontal-stack
            title: Железо
            cards:
              - type: gauge
                name: Загрузка CPU
                unit: '%'
                entity: sensor.processor_use
                severity:
                  green: 0
                  yellow: 60
                  red: 85
              - type: gauge
                name: Температура CPU
                entity: sensor.cpu_temperature
                min: 20
                max: 120
                severity:
                  green: 0
                  yellow: 60
                  red: 80
          - type: horizontal-stack
            cards:
              - type: gauge
                name: Загрузка ОЗУ
                unit: '%'
                entity: sensor.memory_use_percent
                severity:
                  green: 0
                  yellow: 60
                  red: 85
              - type: gauge
                name: Диск заполнен
                unit: '%'
                entity: sensor.disk_use_percent
                severity:
                  green: 0
                  yellow: 60
                  red: 85

          - type: entities
            show_header_toggle: false
            entities:
              - entity: sensor.last_boot_custom
              - entity: sensor.online_custom
              - entity: sensor.time
                name: Текущее время
                icon: mdi:clock-outline
              - entity: sensor.date
                name: Дата
                icon: mdi:calendar-check-outline
              - entity: sensor.rpi_power_status
              - entity: sensor.maria_db_size
                name: Объем БД
                icon: mdi:database

          - type: entities
            title: Резервное копирование
            show_header_toggle: false
            entities:
              - entity: sensor.last_google_backup_train
              - entity: sensor.snapshots_in_google_drive_train
              - entity: sensor.snapshots_in_hassio_train

  - title: Погода
    icon: mdi:weather-partly-snowy-rainy
    cards:
        - type: weather-forecast
          entity: weather.home_assistant

  - title: Освещение
    icon: mdi:lightbulb-group
    cards:
      - type: vertical-stack
        cards:
          - type: markdown
            content: >
               **Светильники**
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.yeelight_rgb_bulb
                name: Лампочка color2
      - type: vertical-stack
        cards:
          - type: markdown
            content: >
               **Скрипты**
          - type: entities
            show_header_toggle: false
            entities:
              - entity: script.unit8_light_on_full
              - entity: script.unit8_light_on_medium
              - entity: script.unit8_light_off

  - title: СС2531 Zigbee
    icon: mdi:zigbee
    cards:
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Добавление устройств**
        - type: entities
          title: Добавление Zigbee устройств
          show_header_toggle: false
          entities:
            - entity: input_boolean.zigbee_permit_join
            - entity: timer.zigbee_permit_join
            - entity: sensor.bridge_state

      - type: vertical-stack
        cards:
          - type: markdown
            content: >
               **Датчики**
          - type: glance
            title: Температура в зале
            entities:
              - entity: sensor.0x00158d000464e067_temperature
                name: Temperature
              - entity: sensor.0x00158d000464e067_humidity
                name: Humidity
              - entity: sensor.0x00158d000464e067_pressure
                name: Pressure
              - entity: sensor.0x00158d000464e067_battery
                name: Battery
              - entity: sensor.0x00158d000464e067_linkquality
                name: Link
          - type: glance
            title: Температура в спальне
            entities:
              - entity: sensor.0x00158d0004658739_temperature
                name: Temperature
              - entity: sensor.0x00158d0004658739_humidity
                name: Humidity
              - entity: sensor.0x00158d0004658739_pressure
                name: Pressure
              - entity: sensor.0x00158d0004658739_battery
                name: Battery
              - entity: sensor.0x00158d0004658739_linkquality
                name: Link

          - type: glance
            title: Протечка 1
            entities:
              - entity: binary_sensor.0x00158d00042f219f_water_leak
                name: Leak
              - entity: sensor.0x00158d00042f219f_battery
                name: Battery
              - entity: sensor.0x00158d00042f219f_linkquality
                name: Link
          - type: glance
            title: Протечка 2
            entities:
              - entity: binary_sensor.0x00158d00042fd07e_water_leak
                name: Leak
              - entity: sensor.0x00158d00042fd07e_battery
                name: Battery
              - entity: sensor.0x00158d00042fd07e_linkquality
                name: Link
          - type: glance
            title: Протечка 3
            entities:
              - entity: binary_sensor.0x00158d00045a552a_water_leak
                name: Leak
              - entity: sensor.0x00158d00045a552a_battery
                name: Battery
              - entity: sensor.0x00158d00045a552a_linkquality
                name: Link

  - title: wi-fi
    icon: mdi:wifi
    cards:
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Wi-Fi розетки и удлинители**
        - type: entities
          show_header_toggle: false
          entities:
            - entity: switch.mi_3usb_strip
              name: Удлинитель Xiaomi c 3 USB
            - entity: sensor.mi_3usb_strip_load
            - entity: switch.mi_usb_socket
              name: Розетка Xiaomi c 2 USB
            - entity: sensor.usb_socket_load

      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Климатическая техника**
        - type: entities
          show_header_toggle: false
          entities:
            - entity: fan.mi_humidifier
              name: Увлажнитель Smartmi
            - entity: sensor.smartmi_speed
            - entity: sensor.smartmi_water
            - entity: sensor.smartmi_temperature
            - entity: sensor.smartmi_humidity

        - type: entities
          show_header_toggle: false
          entities:
            - entity: fan.mi_purifier
              name: Очиститель Xiaomi
            - entity: sensor.purifier_speed
            - entity: sensor.purifier_filter
            - entity: sensor.purifier_temperature
            - entity: sensor.purifier_humidity
            - entity: sensor.purifier_pm25

      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Качество воздуха**
        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.mi_air_co2a
            - entity: sensor.mi_air_pm25
            - entity: sensor.mi_air_tvoc
